Entity/facture.php
<?php

namespace Labo\Bundle\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
// JMS Serializer
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\Accessor;
// Slug
use Gedmo\Mapping\Annotation as Gedmo;

use Labo\Bundle\AdminBundle\Entity\item;
use Labo\Bundle\AdminBundle\Entity\LaboUser;
use Labo\Bundle\AdminBundle\services\aeUnits;

use \DateTime;
use \ReflectionClass;
use \Exception;

/**
 * facture
 * @ORM\EntityListeners({"Labo\Bundle\AdminBundle\services\baseEntityListener"})
 *
 * @ExclusionPolicy("all")
 * @ORM\HasLifecycleCallbacks
 */
abstract class facture {

	/**
	 * @var string
	 * @ORM\Id
	 * @ORM\Column(name="id", type="string", nullable=false, unique=true)
	 * @ORM\GeneratedValue(strategy="NONE")
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 */
	protected $id;

	/**
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\LaboUser", inversedBy="factures")
	 * @ORM\JoinColumn(nullable=false, unique=false)
	 * @Gedmo\SortableGroup
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 * @MaxDepth(2)
	 */
	protected $user;

	/**
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\tier", inversedBy="factures")
	 * @ORM\JoinColumn(nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete"})
	 * @MaxDepth(2)
	 */
	protected $boutique;

	/**
	 * @ORM\Column(type="integer")
	 * https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md
	 * @Gedmo\SortablePosition
	 * @Expose
	 * @Groups({"complete"})
	 */
	protected $position;

	/**
	 * @var string
	 * @ORM\Column(name="frozenlocale", type="string", length=16, nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $frozenlocale;

	/**
	 * @ORM\Column(type="integer")
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 */
	protected $state;

	/**
	 * @var DateTime
	 * @ORM\Column(name="delailivraison", type="datetime", nullable=true)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $delailivraison;

	/**
	 * @var DateTime
	 * @ORM\Column(name="created", type="datetime", nullable=false)
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 */
	protected $created;

	/**
	 * @var string
	 * @ORM\Column(name="panier", type="text", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 * @Accessor(getter="getPanier")
	 */
	protected $panier;

	/**
	 * @var string
	 * @ORM\Column(name="frozenuser", type="text", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 * @Accessor(getter="getFrozenuser")
	 */
	protected $frozenuser;

	/**
	 * @var string
	 * @ORM\Column(name="frozenboutique", type="text", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 * @Accessor(getter="getFrozenuser")
	 */
	protected $frozenboutique;

	/**
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 * @Accessor(getter="getStateslist")
	 */
	protected $stateslist;

	/**
	 * @var string
	 * @ORM\Column(name="deviseslist", type="text", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 * @Accessor(getter="getDeviseslist")
	 */
	protected $deviseslist;

	/**
	 * @Expose
	 * @Groups({"complete", "facture", "ajaxlive"})
	 * @Accessor(getter="getDevise")
	 */
	protected $devise;

	public function __construct() {
		$this->id = null;
		$this->user = null;
		$this->boutique = null;
		$this->position = 0;
		$this->state = 0;
		$this->delailivraison = null;
		$this->created = new DateTime();
		$this->panier = null;
		$this->frozenuser = null;
		$this->frozenboutique = null;
		$this->deviseslist = null;
		$this->devise = null;
		$this->locale = null;
		$this->frozenlocale = null;
	}

	public function __toString() {
		return $this->getId();
	}

	public function getNom() {
		return $this->getId();
	}

	/**
	 * @ORM\PrePersist
	 * NEVER PERSIST IF STATE == 6 !!!
	 * Please, change state before persist
	 */
	public function crashIfState6() {
		if($this->state === 6) {
			$this->setUser($this->user);
			$this->setBoutique($this->boutique);
			throw new Exception("It is impossible to persist a facture with state = 6 !! Please, change state before.", 1);
		}
		return $this;
	}

    // Get class name
    public function getShortName() {
        $class = new ReflectionClass(get_called_class());
        return $class->getShortName();
    }

    // Get class name
    public function getClassName() {
        $class = new ReflectionClass(get_called_class());
        return $class->getName();
    }

	/**
	 * Set id
	 * @param string $numero = null
	 * @return facture
	 */
	public function setId($numero = null) {
		// auto / uniquement à la création
		if($this->getId() == null) {
			$date = new DateTime('NOW');
			$this->created = $date;
			$date = $date->format('-Ymd-His');
			if($numero != null) $numero = '-'.(string)$numero;
			$this->id = 'fac-'.$this->getUser()->getId().$date.$numero;
		}
		return $this;
	}

	/**
	 * Set locale
	 * @param string $locale
	 * @return facture
	 */
	public function setLocale($locale) {
		$this->locale = $locale;
		if($this->frozenlocale === null) $this->frozenlocale = $locale;
		return $this;
	}

	/**
	 * Get locale
	 * @return string 
	 */
	public function getLocale() {
		return $this->locale;
	}

	/**
	 * Set frozenlocale
	 * @param string $frozenlocale
	 * @return facture
	 */
	public function setFrozenlocale($frozenlocale) {
		$this->frozenlocale = $frozenlocale;
		return $this;
	}

	/**
	 * Get frozenlocale
	 * @return string 
	 */
	public function getFrozenlocale() {
		return $this->frozenlocale;
	}


	public function getId() {
		return $this->id;
	}

	/**
	 * Set user
	 * @param User $user
	 * @return facture
	 */
	public function setUser(LaboUser $user) {
		if($this->state !== 6) {
			$user->addFacture($this);
			if($user->hasRole('ROLE_TESTER')) $this->setStateTest();
		} else if($user->getFactures()->contains($this)) {
			$user->removeFacture($this);
		}
		$this->user = $user;
		$this->setPanier($this->user->getPaniers());
		return $this;
	}

	/**
	 * Get user
	 * @return User 
	 */
	public function getUser() {
		return $this->user;
	}

	/**
	 * Set boutique
	 * @param tier $boutique
	 * @return facture
	 */
	public function setBoutique(tier $boutique) {
		if($this->state !== 6) {
			$boutique->addFacture($this);
		} else if($boutique->getFactures()->contains($this)) {
			$boutique->removeFacture($this);
		}
		$this->boutique = $boutique;
		return $this;
	}

	/**
	 * Get boutique
	 * @return tier 
	 */
	public function getBoutique() {
		return $this->boutique;
	}

	/**
	 * Set position
	 * @param integer $position
	 * @return facture
	 */
	public function setPosition($position) {
		$this->position = $position;
		return $this;
	}

	/**
	 * Get position
	 * @return integer
	 */
	public function getPosition() {
		return $this->position;
	}

	/**
	 * Set deviseslist
	 * @param array $deviseslist
	 * @return facture
	 */
	public function setDeviseslist($deviseslist) {
		$this->deviseslist = serialize($deviseslist);
		return $this;
	}

	/**
	 * Get deviseslist
	 * @return array
	 */
	public function getDeviseslist() {
		return unserialize($this->deviseslist);
	}

	/**
	 * Get devise
	 * @return array
	 */
	public function getDevise() {
		$devises = $this->getDeviseslist();
		return $devises[$this->getFrozenlocale()];
	}

	/**
	 * Set state
	 * @param integer $state
	 * @return facture
	 */
	public function setState($state) {
		if(!array_key_exists($state, $this->getStateslist())) {
			throw new Exception('Facture::setState() : state '.json_encode($state).' does not exist. Choose it in this list: '.json_encode(array_keys($this->getStateslist())).', please.', 1);
		} else {
			$this->state = $state;
			if($this->state === 6) {
				if($this->getUser() !== null) $this->setUser($this->getUser());
				if($this->getBoutique() !== null) $this->setBoutique($this->getBoutique());
			}
		}
		return $this;
	}

	/**
	 * Get state
	 * @return integer
	 */
	public function getState() {
		return $this->state;
	}

	/**
	 * Get state name
	 * @return string
	 */
	public function getStatename() {
		return $this->getStateslist()[$this->state]['name'];
	}

	/**
	 * Get state color
	 * @return string
	 */
	public function getStatecolor() {
		return $this->getStateslist()[$this->state]['color'];
	}

	/**
	 * Get state
	 * @return integer
	 */
	public function getStateslist() {
		$this->stateslist = array(
			0 => array(
				'name' => 'state.preparation',
				'color' => 'danger',
				),
			1 => array(
				'name' => 'state.devis',
				'color' => 'warning',
				),
			2 => array(
				'name' => 'state.valid',
				'color' => 'success',
				),
			3 => array(
				'name' => 'state.archived',
				'color' => 'muted',
				),
			4 => array(
				'name' => 'state.canceled',
				'color' => 'muted',
				),
			5 => array(
				'name' => 'state.test',
				'color' => 'info',
				),
			6 => array( // TEMP PANIER : jamais persistée !!!
				'name' => 'state.TEMP',
				'color' => 'info',
				),
			);
		return $this->stateslist;
	}

	public function setStatePrepar() { $this->setState(0); }
	public function setStateDevis() { $this->setState(1); }
	public function setStateValid() { $this->setState(2); }
	public function setStateArchived() { $this->setState(3); }
	public function setStateCanceled() { $this->setState(4); }
	public function setStateTest() { $this->setState(5); }
	public function setStateTEMP() { $this->setState(6); }


	/**
	 * Set details of articles
	 * CAUTION !!! use JMSserializer (with 'json' and group 'facture') on an array of panier
	 * @param string $panier
	 * @return facture
	 */
	public function setPanier($panier) {
		$this->panier = $panier;
	}

	/**
	 * get articles detail
	 * @return array
	 */
	public function getPanier($asJson = false) {

Entity/tier.php
<?php

namespace Labo\Bundle\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
// JMS Serializer
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\Accessor;

use Labo\Bundle\AdminBundle\Entity\nested;
use Labo\Bundle\AdminBundle\Entity\calendar;
use site\adminsiteBundle\Entity\categorie;
use site\adminsiteBundle\Entity\adresse;
use site\adminsiteBundle\Entity\image;
use site\adminsiteBundle\Entity\facture as siteFacture; // facture

use \DateTime;
use \Exception;

/**
 * tier
 * 
 * @ORM\Entity(repositoryClass="Labo\Bundle\AdminBundle\Entity\tierRepository")
 * @ORM\HasLifecycleCallbacks
 * 
 * @ExclusionPolicy("all")
 * 
 * @ORM\DiscriminatorColumn(name="class_name", type="string")
 * @ORM\InheritanceType("JOINED")
 */
abstract class tier extends nested {

	/**
	 * @var integer
	 * @ORM\Id
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $id;

	/**
	 * @var integer - PROPRIÉTAIRE
	 * @ORM\OneToOne(targetEntity="site\adminsiteBundle\Entity\adresse", cascade={"all"}, inversedBy="tier")
	 * @ORM\JoinColumn(nullable=true, unique=false, onDelete="SET NULL")
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $adresse;

	/**
     * @ORM\OneToMany(targetEntity="Labo\Bundle\AdminBundle\Entity\calendar", orphanRemoval=true, mappedBy="tier")
	 * @ORM\JoinColumn(nullable=true, unique=true, onDelete="SET NULL")
	 * @ORM\OrderBy({"startDate" = "DESC"})
	 */
	protected $calendars;

	/**
     * @ORM\OneToOne(targetEntity="site\adminsiteBundle\Entity\image", orphanRemoval=true, cascade={"all"})
	 * @ORM\JoinColumn(nullable=true, unique=true, onDelete="SET NULL")
	 */
	protected $logo;

	/**
	 * @var string
	 * @ORM\Column(name="telfixe", type="string", length=14, nullable=true, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $telfixe;

	/**
	 * @var string
	 * @ORM\Column(name="mobile", type="string", length=14, nullable=true, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 */
	protected $mobile;

	/**
	 * @var string
	 * @ORM\Column(name="email", type="string", length=128, nullable=true, unique=false)
	 * @Expose
	 * @Groups({"complete", "facture"})
	 * @Assert\Email(strict=true, message="Le format de l'email est incorrect")
	 * @Assert\Email(checkMX=true, message="Aucun serveur mail n'a été trouvé pour ce domaine")
	 */
	protected $email;

	/**
	 * - INVERSE
	 * @ORM\OneToMany(targetEntity="site\adminsiteBundle\Entity\facture", mappedBy="boutique", cascade={"persist", "remove"})
	 * @ORM\JoinColumn(referencedColumnName="id", nullable=true, onDelete="SET NULL")
	 * @ORM\OrderBy({"created" = "DESC"})
	 * @Expose
	 * @Groups({"complete"})
	 */
	protected $factures;


	public function __construct() {
		parent::__construct();
		$this->adresse = null;
		$this->telfixe = null;
		$this->mobile = null;
		$this->email = null;
		$this->calendars = new ArrayCollection();
		$this->factures = new ArrayCollection();
	}

	/**
	 * Renvoie l'image principale
	 * @return image
	 */
	public function getMainMedia() {
		if($this->getLogo() !== null) return $this->getLogo();
		if($this->getImage() !== null) return $this->getImage();
		return null;
	}

	/**
	 * Set adresse - PROPRIÉTAIRE
	 * @param adresse $adresse
	 * @return tier
	 */
	public function setAdresse(adresse $adresse = null) {
		// $adresse->setTier($this);
		$this->adresse = $adresse;
		return $this;
	}

	/**
	 * Get adresse - PROPRIÉTAIRE
	 * @return adresse 
	 */
	public function getAdresse() {
		return $this->adresse;
	}

	/**
	 * Set logo - PROPRIÉTAIRE
	 * @param image $logo
	 * @return tier
	 */
	public function setLogo(image $logo = null) {
		if($this->logo != null && $logo == null) {
			$this->logo->setElement(null);
		}
		$this->logo = $logo;
		if($this->logo != null) {
			$this->logo->setElement($this, 'logo');
			$this->logo->setStatut($this->getStatut());
		}
		return $this;
	}

	/**
	 * Get logo - PROPRIÉTAIRE
	 * @return image 
	 */
	public function getLogo() {
		return $this->logo;
	}

	protected function formatTel($tel) {
		// return preg_replace_callback(
		// 	'#(\d)#',
		// 	function($matches) {
		// 		return $matches[0];
		// 	},
		// 	$tel
		// );
		return $tel;
	}

	/**
	 * Get telfixe
	 * @return string
	 */
	public function getTelfixe() {
		return $this->formatTel($this->telfixe);
	}

	/**
	 * Set telfixe
	 * @param string $telfixe
	 * @return tier
	 */
	public function setTelfixe($telfixe) {
		$this->telfixe = $this->formatTel($telfixe);
		return $this;
	}


	/**
	 * Get mobile
	 * @return string
	 */
	public function getMobile() {
		return $this->formatTel($this->mobile);
	}

	/**
	 * Set mobile
	 * @param string $mobile
	 * @return tier
	 */
	public function setMobile($mobile) {
		$this->mobile = $this->formatTel($mobile);
		return $this;
	}

	/**
	 * Get email
	 * @return string
	 */
	public function getEmail() {
		return $this->email;
	}

	/**
	 * Set email
	 * @param string $email
	 * @return tier
	 */
	public function setEmail($email) {
		$this->email = $email;
		return $this;
	}

	/**
	 * Get calendars
	 * @return arrayCollection
	 */
	public function getCalendars() {
		return $this->calendars;
	}

	/**
	 * Set calendars
	 * @param ArrayCollection $calendars
	 * @return tier
	 */
	public function setCalendars(ArrayCollection $calendars) {
		$this->calendars = $calendars;
		return $this;
	}

	/**
	 * add calendar
	 * @param calendar $calendar
	 * @return tier
	 */
	public function addCalendar(calendar $calendar) {
		$this->calendars->add($calendar);
		return $this;
	}

	/**
	 * remove calendar
	 * @param calendar $calendar
	 * @return boolean
	 */
	public function removeCalendar(calendar $calendar) {
		return $this->calendars->removeElement($calendar);
	}

	/**
	 * Get factures - INVERSE
	 * @return ArrayCollection 
	 */
	public function getFactures() {
		return $this->factures;
	}

	/**
	 * Set factures - INVERSE
	 * @param ArrayCollection $factures
	 * @return tier
	 */
	public function setFactures(ArrayCollection $factures) {
		$this->factures = $factures;
		return $this;
	}

	/**
	 * Add facture - INVERSE
	 * @param siteFacture $facture
	 * @return tier
	 */
	public function addFacture(siteFacture $facture) {
		if(!$this->factures->contains($facture)) $this->factures->add($facture);
		return $this;
	}

	/**
	 * Remove facture - INVERSE
	 * @param siteFacture $facture
	 * @return boolean
	 */
	public function removeFacture(siteFacture $facture) {
		return $this->factures->removeElement($facture);
	}


}

Resources/views/blocks/dump.html.twig
{# {{ dump(data) }} #}

Resources/views/blocks/entite_interdit.html.twig
<div class="alert alert-danger col-sm-8 col-sm-offset-2 m-t-lg">
	<h3 class='text-center'>
		<i class="fa fa-ban fa-5x m-b-lg"></i>
		<p>{{ UCfirst('grants.no_access'|trans({'%name%': entite.nom|default('ID#' ~ entite.id)}, entite.shortName|default('element')))|raw }}</p>
	</h3>
</div>

Resources/views/blocks/favicon.html.twig
{% block faviconPrint %}
	{% if app.session.get('sitedata') != null %}
		{% if app.session.get('sitedata').favicon_id|default(null) != null %}
		{% set favicon16 = imageB64sized(app.session.get('sitedata').favicon_id, 16, 16, 'cut') %}
		{% endif %}
		{% if favicon16|default(null) != null %}
		<link rel="shortcut icon" type="image/x-icon" href="{{ favicon16 }}">
		<link rel="icon" type="image/png" href="{{ favicon16 }}">
		<link rel="apple-touch-icon" href="{{ favicon16 }}">
		{% else %}
		<link rel="shortcut icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
		<link rel="apple-touch-icon" href="{{ asset('favicon.png') }}">
		{% endif %}
	{% else %}
		<link rel="shortcut icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
		<link rel="apple-touch-icon" href="{{ asset('favicon.png') }}">
	{% endif %}
{% endblock faviconPrint %}

Resources/views/blocks/footer.html.twig
<div class="pull-right">
	<small>{{ 'footer.generation'|trans|capitalize }} </small><a href="http://wrapbootstrap.com/preview/WB0R5L90S" target='_blank'><strong class='text-muted'>INSPINIA+ Admin Theme</strong></a>
</div>
<div>
	<strong>Aequation-Webdesign</strong> {{ 'footer.rights'|trans|capitalize }} &copy; {{ annee() }}
</div>

Resources/views/blocks/itemBloc.html.twig
{% macro bloc1(item) %}
<div class="col-sm-6 col-md-4 col-lg-3">
	<div class="ibox-content text-center" style="border:1px solid #999;">
		<h3 class="ellipsis m-t-none">{{ item.nom }}</h3>
		<div class="m-b-sm" style="height:96px;">
			<a href="{{ path('siteadmin_entite', {entite: item.shortName, id: item.id, action: 'show'}) }}">
				{% if item.mainMedia.isScreenableImage|default(null) != null %}
				<img alt="image" src="{{ item.mainMedia.imgThumbnail(96,96,'cut') }}" class="img-rounded">
				{% else %}
				<i class="fa fa-ban fa-5x text-muted m-t-sm"></i>
				{% endif %}
			</a>
		</div>
		{% if item.shortName in ['pageweb'] %}
		<p class="font-bold ellipsis">{{ item.title|default('…') }}</p>
		{% elseif item.shortName in ['article', 'fiche'] %}
		<p class="font-bold ellipsis">{{ item.accroche|default('…') }}</p>
		{% else %}
		<p class="font-bold ellipsis">…</p>
		{% endif %}
		<div class="text-center btn-group btn-block">
			<a href="{{ path('siteadmin_entite', {entite: item.shortName, id: item.id, action: 'show'}) }}" class="btn btn-xs btn-white col-xs-6 m-b-none" data-toggle="tooltip" data-placement="bottom" title="{{ UCfirst('moredetails'|trans({'%name%': item.nom}, item.shortName)) }}"><i class="fa fa-eye icon-wait-on-click"></i></a>
			<a href="{{ path('siteadmin_entite', {entite: item.shortName, id: item.id, action: 'edit'}) }}" class="btn btn-xs btn-white col-xs-6 m-b-none" data-toggle="tooltip" data-placement="bottom" title="{{ UCfirst('actions.modifierName'|trans({'%name%': item.nom})) }}"><i class="fa fa-pencil icon-wait-on-click"></i></a>
		</div>
	</div>
</div>
{% endmacro %}

{% macro bloc2(item) %}
<div class="col-sm-6 col-md-4 col-lg-3">
	<div class="widget white-bg" style="border:1px solid #999;">
		<div class="row vertical-align">
			<div class="col-xs-4">
				{% if item.mainMedia.isScreenableImage|default(null) != null %}
				<img alt="image" src="{{ item.mainMedia.imgThumbnail(64,64,'cut') }}" class="img-responsive img-rounded">
				{% else %}
				<i class="fa fa-ban fa-3x text-muted"></i>
				{% endif %}
			</div>
			<div class="col-xs-8 text-right">
				<h4 class="font-bold ellipsis">{{ item.nom }}</h4>
				{% if item.shortName in ['pageweb'] %}
				<small class="text-muted ellipsis">{{ item.title|default('…') }}</small>
				{% elseif item.shortName in ['article', 'fiche'] %}
				<small class="text-muted ellipsis">{{ item.accroche|default('…') }}</small>
				{% else %}
				<small class="text-muted ellipsis">…</small>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endmacro %}

Resources/views/blocks/sidebar.html.twig
{% import 'LaboAdminBundle:blocks:menumacro.html.twig' as menumacro %}
{% import 'LaboAdminBundle:blocks:actions.html.twig' as actions %}

<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element">
					<span>
						<a {{ actions.publicHref() }}>
							{% if sitedata.adminLogo|default(null) != null %}
							<img alt="image" class="" src="{{ sitedata.adminLogo.img }}" />
							{% else %}
							{% if fileExists(asset('bundles/' ~ LaboAdminBundle|default('LaboAdminBundle') ~ '/images/logo_admin.png')) %}
							<img alt="image" class="" src="{{ asset('bundles/' ~ LaboAdminBundle|default('LaboAdminBundle') ~ '/images/logo_admin.png') }}" />
							{% else %}
							<img alt="image" class="" src="{{ asset('bundles/laboadmin/images/logo_admin.png') }}" />
							{% endif %}
							{% endif %}
						</a>
					</span>
					{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<span class="clear">
							{% if sitedata.nom|default(null) != null %}
							<span class="block m-t-xs"> <strong class="font-bold">{{ UCfirst(sitedata.nom) }}</strong></span>
							{% else %}
							<span class="block m-t-xs"> <strong class="font-bold">{{ UCfirst('admin'|trans) }}</strong></span>
							{% endif %}
							<span class="text-muted text-xs block">{{ app.user.username|default('anon.') }} <b class="caret"></b></span> 
						</span>
					</a>
					<ul class="dropdown-menu animated fadeInRight m-t-xs">
						<li>
							{% if app.user.adminhelp %}{% set adminhelp = 'swh-on' %}{% else %}{% set adminhelp = 'swh-off' %}{% endif %}
							<a class="switch-adminhelp {{ adminhelp }}" data-txt-target="span.helpinmenu" data-txt-swh-seton="{{ 'actions.help.setOn'|trans({}, 'siteUserBundle') }}" data-txt-swh-setoff="{{ 'actions.help.setOff'|trans({}, 'siteUserBundle') }}">
								<i class="fa fa-support m-r-xs"></i><span class="helpinmenu"></span>
							</a>
						</li>
						<li class="divider"></li>
						<li><a href="{{ path('fos_user_profile_show') }}"><i class="fa fa-user m-r-xs"></i>{{ UCfirst('profile.name'|trans({}, 'siteUserBundle')) }}</a></li>
						<li><a href="{{ path('fos_user_security_logout') }}"><i class="fa fa-sign-out m-r-xs"></i>{{ UCfirst('layout.logout'|trans({}, 'siteUserBundle')) }}</a></li>
					</ul>
					{% endif %}
				</div>
				<div class="logo-element">
					<i class="fa fa-desktop visible-lg"></i>
					<i class="fa fa-laptop visible-md"></i>
					<i class="fa fa-tablet visible-sm"></i>
					<i class="fa fa-mobile-phone visible-xs"></i>
				</div>
			</li>
			{{ menumacro.menu_Admin() }}
		</ul>
	</div>
</nav>