Entity/calendar.php
<?php

namespace Labo\Bundle\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
// JMS Serializer
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\Accessor;
// Slug
use Gedmo\Mapping\Annotation as Gedmo;

use Labo\Bundle\AdminBundle\Entity\baseEntity;
use Labo\Bundle\AdminBundle\Entity\tier;
use Labo\Bundle\AdminBundle\Entity\baseevenement;
use Labo\Bundle\AdminBundle\Entity\LaboUser;

use \DateTime;

/**
 * calendar
 * 
 * @ORM\Entity(repositoryClass="Labo\Bundle\AdminBundle\Entity\calendarRepository")
 * @ORM\EntityListeners({"Labo\Bundle\AdminBundle\services\baseEntityListener"})
 * 
 * @ORM\DiscriminatorColumn(name="class_name", type="string")
 * @ORM\InheritanceType("JOINED")
 * 
 * @ExclusionPolicy("all")
 * @ORM\HasLifecycleCallbacks
 */
abstract class calendar extends baseEntity {

	// http://php.net/manual/en/class.datetime.php#datetime.constants.types
	// const FC_FORMAT = DateTime::ATOM;
	// const FC_FORMAT = 'Y-m-d H:i:s';

	/**
	 * @var integer
	 * @ORM\Id
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 * @Accessor(getter="getIdForFC")
	 */
	protected $id;

	/**
	 * @var DateTime
	 * @ORM\Column(name="start", type="datetime", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete"})
	 */
	protected $startDate;

	/**
	 * @var DateTime
	 * @ORM\Column(name="end", type="datetime", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete"})
	 */
	protected $endDate;

	/**
	 * @var boolean
	 * @ORM\Column(name="allday", type="boolean", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 */
	protected $allDay;

	/**
	 * @var string
	 * @ORM\Column(name="url", type="string", nullable=true, unique=false)
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 */
	protected $url;

	/**
	 * @var string
	 * @ORM\Column(name="color", type="string", length=32, nullable=true, unique=false)
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 */
	protected $color;

	/**
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\tier", inversedBy="calendars")
	 * @ORM\JoinColumn(nullable=true, unique=false, onDelete="SET NULL")
	 * @Expose
	 * @Groups({"complete"})
	 * @MaxDepth(2)
	 */
	protected $tier;

	/**
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\baseevenement", inversedBy="calendars")
	 * @ORM\JoinColumn(nullable=true, unique=false, onDelete="SET NULL")
	 * @Expose
	 * @Groups({"complete"})
	 * @MaxDepth(2)
	 */
	protected $evenement;

	/**
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\LaboUser", inversedBy="calendars")
	 * @ORM\JoinColumn(nullable=true, unique=false, onDelete="SET NULL")
	 * @Expose
	 * @Groups({"complete"})
	 * @MaxDepth(2)
	 */
	protected $usercal;

	/**
	 * @Expose
	 * @Groups({"fullcalendar"})
	 * @Accessor(getter="getStartFcFormat")
	 */
	protected $start;

	/**
	 * @Expose
	 * @Groups({"fullcalendar"})
	 * @Accessor(getter="getTitle")
	 */
	protected $title;

	/**
	 * @Expose
	 * @Groups({"fullcalendar"})
	 * @Accessor(getter="getEndFcFormat")
	 */
	protected $end;

	/**
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 * @Accessor(getter="getOwner")
	 */
	protected $owner;

	/**
	 * @Expose
	 * @Groups({"complete", "fullcalendar"})
	 * @Accessor(getter="getLocale")
	 */
	protected $locale;


	public function __construct() {
		parent::__construct();
		$this->nom = '';
		$this->startDate = new DateTime();
		$this->endDate = null;
		$this->allDay = false;
		$this->url = null;
		$this->color = null;
		$this->tier = null;
		$this->evenement = null;
		$this->usercal = null;
	}

	public function __toString() {
		return $this->getNom();
	}

	public function getIdForFC() {
		if($this->id === null) return rand(100000, 999999).'#';
		return $this->id.'@';
	}

	/**
	 * Un élément par défaut dans la table est-il optionnel ?
	 * @return boolean
	 */
	public function isDefaultNullable() {
		return true;
	}

	/**
	 * Peut'on attribuer plusieurs éléments par défaut ?
	 * true 		= illimité
	 * integer 		= nombre max. d'éléments par défaut
	 * false, 0, 1 	= un seul élément
	 * @return boolean
	 */
	public function isDefaultMultiple() {
		return true;
	}

	/**
	 * Get title (nom)
	 * @return string 
	 */
	public function getTitle() {
		return $this->getNom();
	}

	/**
	 * Get start
	 * @return string 
	 */
	public function getStartFcFormat() {
		return $this->startDate->format(DATE_ATOM);
	}
	/**
	 * Get startDate
	 * @return DateTime 
	 */
	public function getStartDate() {
		return $this->startDate;
	}
	/**
	 * Set startDate
	 * @param DateTime $startDate
	 * @return calendar 
	 */
	public function setStartDate(DateTime $startDate) {
		$this->startDate = $startDate;
		return $this;
	}

	/**
	 * Get end
	 * @return string
	 */
	public function getEndFcFormat() {
		return $this->endDate instanceOf DateTime ? $this->endDate->format(DATE_ATOM) : null;
	}
	/**
	 * Get endDate
	 * @return DateTime  / null
	 */
	public function getEndDate() {
		return $this->endDate;
	}
	/**
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	 * Verif endDate
	 * @return calendar
	 */
	public function verifDates() {
		if($this->endDate === null) {
			$this->endDate = clone $this->startDate;
			$this->endDate->modify('+1 hour');
		}
		if($this->endDate < $this->startDate) {
			$this->endDate = clone $this->startDate;
			$this->endDate->modify('+1 hour');
		}
		if($this->allDay) {
			$this->startDate->modify('today');
			$this->endDate->modify('today');
		}
		return $this;
	}
	/**
	 * Set endDate
	 * @param DateTime $endDate = null
	 * @return calendar
	 */
	public function setEndDate(DateTime $endDate = null) {
		$this->endDate = $endDate;
		// $this->verifDates();
		return $this;
	}

	/**
	 * Get allDay
	 * @return boolean 
	 */
	public function getAllDay() {
		return $this->allDay;
	}
	/**
	 * Set allDay
	 * @param boolean $allDay
	 * @return calendar 
	 */
	public function setAllDay($allDay) {
		$this->allDay = $allDay;
		return $this;
	}

	/**
	 * Get url
	 * @return string 
	 */
	public function getUrl() {
		return $this->url;
	}
	/**
	 * Set url
	 * @param string $url = null
	 * @return calendar 
	 */
	public function setUrl($url = null) {
		$this->url = $url;
		return $this;
	}

	/**
	 * Get color
	 * @return string 
	 */
	public function getColor() {
		return $this->color;
	}
	/**
	 * Set color
	 * @param string $color = null
	 * @return calendar 
	 */
	public function setColor($color = null) {
		$this->color = $color;
		return $this;
	}


	public function getOwnerObject() {
		if($this->tier instanceOf tier) return $this->tier;
		if($this->evenement instanceOf baseevenement) return $this->evenement;
		if($this->usercal instanceOf LaboUser) return $this->usercal;
		return null;
	}

	public function getOwner() {
		$prop = $this->getOwnerObject();
		if($prop !== null) return array(
			'slug' => $prop->getSlug(),
			'class' => $prop->getShortName(),
		);
		return $prop;
	}

	public function removeOwner() {
		if($this->getOwnerObject() instanceOf tier) return $this->removeTier();
			else if($this->getOwnerObject() instanceOf baseevenement) return $this->removeEvenement();
			else if($this->getOwnerObject() instanceOf LaboUser) return $this->removeUsercal();
		return $this;
	}

	/**
	 * set owner
	 * @param object $owner = null
	 * @return calendar
	 */
	public function setOwner($owner = null) {
		if($owner instanceOf tier) return $this->setTier($owner);
			else if($owner instanceOf baseevenement) return $this->setEvenement($owner);
			else if($owner instanceOf LaboUser) return $this->setUsercal($owner);
			else if($owner === null) $this->removeOwner();
			else throw new Exception("Owner for calendar is not valid! Must be instance of tier, baseevenement or LaboUser, or NULL.", 1);
		return $this;
	}

	/**
	 * set tier
	 * @param tier $tier
	 * @return tier / null
	 */
	public function getTier() {
		return $this->tier;
	}

	/**
	 * set tier
	 * @param tier $tier = null
	 * @return calendar
	 */
	public function setTier(tier $tier = null) {
		$this->removeOwner();
		if($tier instanceOf tier) {
			$this->tier = $tier;
			$tier->addCalendar($this);
		}
		return $this;
	}

	/**
	 * @ORM\PreRemove
	 * Remove tier
	 * @return boolean
	 */
	public function removeTier() {
		$r = false;
		if($this->tier instanceOf tier) $r = $this->tier->removeCalendar($this);
		if($r) $this->tier = null;
		return $r;
	}

	/**
	 * get baseevenement cal
	 * @return evenement / null
	 */
	public function getEvenement() {
		return $this->evenement;
	}

	/**
	 * set baseevenement cal
	 * @param baseevenement $evenement = null
	 * @return calendar
	 */
	public function setEvenement(baseevenement $evenement = null) {
		$this->removeOwner();
		if($evenement instanceOf baseevenement) {
			$this->evenement = $evenement;
			$evenement->addCalendar($this);
		}
		return $this;
	}

	/**
	 * @ORM\PreRemove
	 * Remove baseevenement
	 * @return boolean
	 */
	public function removeEvenement() {
		$r = false;
		if($this->evenement instanceOf baseevenement) $r = $this->evenement->removeCalendar($this);
		if($r) $this->evenement = null;
		return $r;
	}

	/**
	 * get user cal
	 * @return LaboUser / null
	 */
	public function getUsercal() {
		return $this->usercal;
	}

	/**
	 * set user cal
	 * @param LaboUser $usercal = null
	 * @return calendar
	 */
	public function setUsercal(LaboUser $usercal = null) {
		$this->removeOwner();
		if($usercal instanceOf LaboUser) {
			$this->usercal = $usercal;
			$usercal->addCalendar($this);
		}
		return $this;
	}

	/**
	 * @ORM\PreRemove
	 * Remove user cal
	 * @return boolean
	 */
	public function removeUsercal() {
		$r = false;

Entity/panier.php
<?php

namespace Labo\Bundle\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
// JMS Serializer
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\Accessor;
// Slug
use Gedmo\Mapping\Annotation as Gedmo;

use Labo\Bundle\AdminBundle\Entity\item;
use Labo\Bundle\AdminBundle\Entity\LaboUser;
use Labo\Bundle\AdminBundle\services\aeUnits;

use \DateTime;
use \ReflectionClass;

/**
 * panier
 * 
 * @ORM\EntityListeners({"Labo\Bundle\AdminBundle\services\baseEntityListener"})
 * @ExclusionPolicy("all")
 * @ORM\HasLifecycleCallbacks
 */
abstract class panier {

	/**
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="Labo\Bundle\AdminBundle\Entity\LaboUser", inversedBy="paniers")
	 * @ORM\JoinColumn(nullable=false, unique=false)
	 * @Gedmo\SortableGroup
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 * @MaxDepth(2)
	 */
	protected $user;

	/**
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 * @MaxDepth(2)
	 */
	protected $article;

	/**
	 * @ORM\Column(type="integer")
	 * https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md
	 * @Gedmo\SortablePosition
	 * @Expose
	 * @Groups({"complete", "ajaxlive"})
	 */
	protected $position;

	/**
	 * @var integer
	 * @ORM\Column(name="quantite", type="integer", nullable=false, unique=false)
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 */
	protected $quantite;

	/**
	 * @var DateTime
	 * @ORM\Column(name="created", type="datetime", nullable=false)
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 */
	protected $created;

	/**
	 * @var DateTime
	 * @ORM\Column(name="updated", type="datetime", nullable=true)
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 */
	protected $updated;

	/**
	 * @var string
	 * @ORM\Column(name="uniquid", type="string", nullable=false, unique=true)
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 */
	protected $uniquid;

	/**
	 * @Expose
	 * @Groups({"complete", "facture"})
	 * @Accessor(getter="getId")
	 */
	protected $id;

	/**
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 * @Accessor(getter="getLocale")
	 */
	protected $locale;

	/**
	 * @Expose
	 * @Groups({"complete", "ajaxlive", "facture"})
	 * @Accessor(getter="getPrixtotaltxt")
	 */
	protected $prixTotal;
	/**
	 * @Expose
	 * @Groups({"complete", "facture"})
	 * @Accessor(getter="getPrixUnitText")
	 */
	protected $prixTotalTxt;

	public function __construct() {
		$this->created = new DateTime();
		$this->user = null;
		$this->article = null;
		$this->updated = null;
		$this->quantite = 0;
		$this->position = 0;
		$this->uniquid = null;
		$this->locale = 'fr';
	}

	public function __toString() {
		return $this->getQuantite()." x ".$this->getArticle()->getNom();
	}

    // Get class name
    public function getShortName() {
        $class = new ReflectionClass(get_called_class());
        return $class->getShortName();
    }

    // Get class name
    public function getClassName() {
        $class = new ReflectionClass(get_called_class());
        return $class->getName();
    }


	public function getId() {
		$array = $this->getArrayForId();
		foreach($array as $key => $item) {
			if(is_object($item)) if(method_exists($item, 'getId'))$array[$key] = $item->getId();
		}
		return json_encode($array);
	}

	public function getArrayForId() {
		return array(
			'user' => $this->getUser(),
			'article' => $this->getArticle(),
		);
	}

	/**
	 * Set locale
	 * @param string $locale
	 * @return baseEntity
	 */
	public function setLocale($locale) {
		$this->locale = $locale;
		return $this;
	}

	/**
	 * Get locale
	 * @return string 
	 */
	public function getLocale() {
		return $this->locale;
	}

	/**
	 * @ORM\PrePersist()
	 * @ORM\PreUpdate()
	 * Set uniquid
	 * @return panier
	 */
	public function setUniquid() {
		$this->uniquid = $this->getId();
	}

	public function getUniquid() {
		return $this->uniquid;
	}

	/**
	 * Set user
	 * @param User $user
	 * @return panier
	 */
	public function setUser(LaboUser $user) {
		$user->addPanier($this);
		$this->user = $user;
		return $this;
	}

	/**
	 * Get user
	 * @return User 
	 */
	public function getUser() {
		return $this->user;
	}

	/**
	 * Set article
	 * @param item $article
	 * @return panier
	 */
	public function setArticle(item $article) {
		$this->article = $article;
	
		return $this;
	}

	/**
	 * Set position
	 * @param integer $position
	 * @return panier
	 */
	public function setPosition($position) {
		$this->position = $position;
	}

	/**
	 * Get position
	 * @return integer
	 */
	public function getPosition() {
		return $this->position;
	}

	public function calculPrix($prix) {
		$aeUnits = new aeUnits;
		$ratio = $aeUnits->getRatio($this->article->getUnitPrix(), $this->article->getUnit());
		return $prix * $ratio * $this->getQuantite();
	}

	/**
	 * Get prixtotal
	 * @return float
	 */
	public function getPrixtotal() {
		return $this->calculPrix($this->article->getPrix());
	}

	/**
	 * Get prixtotal
	 * @return float
	 */
	public function getPrixtotalHT() {
		return $this->calculPrix($this->article->getPrixHT());
	}

	/**
	 * Get getPrixtotaltxt
	 * @return string
	 */
	public function getPrixtotaltxt() {
		return number_format($this->getPrixtotal(), 2, ",", "");
	}

	/**
	 * Get text of prix and devise (please, use raw filter in twig)
	 * @return string (of html code)
	 */
	public function getPrixUnitText() {
		$devise = $this->getArticle()->getDevise()['symb'];
		return $this->getPrixtotaltxt().'<small><sup>'.$devise.'TTC</sup></small>';
	}

	/**
	 * Get getPrixtotaltxt
	 * @return string
	 */
	public function getPrixtotalHTtxt() {
		return number_format($this->getPrixtotalHT(), 2, ",", "");
	}

	/**
	 * Get article
	 * @return item 
	 */
	public function getArticle() {
		return $this->article;
	}

	/**
	 * Set quantite
	 * @param integer $quantite
	 * @return panier
	 */
	public function setQuantite($quantite) {
		$this->quantite = $quantite;
		return $this;
	}

	/**
	 * ajouteQuantite
	 * @param integer $quantite
	 * @return panier
	 */
	public function ajouteQuantite($quantite) {
		$this->quantite += $quantite;
		return $this;
	}

	/**
	 * retireQuantite
	 * @param integer $quantite
	 * @return panier
	 */
	public function retireQuantite($quantite) {
		$this->quantite -= $quantite;
		if($this->quantite < 0) $this->quantite = 0;
		return $this;
	}

	/**
	 * Get quantite
	 * @return integer 
	 */
	public function getQuantite() {
		return $this->quantite;
	}

	/**
	 * Set created
	 * @param DateTime $created
	 * @return panier
	 */
	public function setCreated(DateTime $created) {
		$this->created = $created;
		return $this;
	}

	/**
	 * Get created
	 * @return DateTime 
	 */
	public function getCreated() {
		return $this->created;
	}

	/**
	 * @ORM\PreUpdate
	 */
	public function updateDate() {
		$this->setUpdated(new DateTime());
	}

	/**
	 * Set updated
	 * @param DateTime $updated
	 * @return panier
	 */
	public function setUpdated(DateTime $updated) {
		$this->updated = $updated;
		return $this;
	}

	/**
	 * Get updated
	 * @return DateTime 
	 */
	public function getUpdated() {
		return $this->updated;
	}



}

Resources/views/calendar/calendar_boutique_edit.html.twig
{% extends 'LaboAdminBundle:calendar:calendar_tier_edit.html.twig' %}

Resources/views/calendar/calendar_boutique_viewer.html.twig
{% extends 'LaboAdminBundle:calendar:calendar_tier_viewer.html.twig' %}

Resources/views/calendar/calendar_evenement_edit.html.twig
{% extends 'LaboAdminBundle::page_admin_generic.html.twig' %}
{% set cssjsloads = 'simple' %}
{% set DEVMODE = (app.environment in ['DEV', 'TEST']) or (is_granted('ROLE_SUPER_ADMIN')) %}
{% import 'LaboAdminBundle:blocks:actions.html.twig' as actions %}

{% block page_heading %}
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-12 m-t-xs">
		<div class="row">
			<div class="col-md-9">
				<h2>{{ actions.htmlicon('calendar', 1, ['m-r-xs']) }}Agenda</h2>
				<ol class="breadcrumb ellipsis">
					<li><a href="{{ path('siteadmin_homepage') }}"><strong>{{ UCfirst('administration'|trans) }}</strong></a></li>
					<li><a href="{{ path('siteadmin_calendar_viewer', {itemSlug: event.ownerObject.slug, class: event.ownerObject.shortname}) }}"><strong>Agenda {{ event.ownerObject.nom }}</strong></a></li>
					<li>Modification {{ event.nom|default('') }}</li>
				</ol>
			</div>
			{% block buttons %}
			{% endblock buttons %}
		</div>
	</div>
</div>
{% endblock page_heading %}

{% block content %}
	{% if event != null %}
	<div class="row animated fadeInDown">
		<div class="col-sm-12">
			{% block ibox %}
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Calendar {{ event.ownerObject.nom }} : {{ event.nom }}</h5>
				</div>
				<div class="ibox-content">
					{# {{ dump(event) }} #}
				</div>
			</div>
			{% endblock ibox %}
		</div>
	</div>
	{% else %}
	<h2>Cet élément <strong>{{ eventSlug|json_encode }}</strong> est introuvable.</h2>
	{% endif %}
	{# {{ dump(test) }} #}
{% endblock content %}

Resources/views/calendar/calendar_evenement_viewer.html.twig
{% extends 'LaboAdminBundle:calendar:calendar_tier_viewer.html.twig' %}

Resources/views/calendar/calendar_tier_edit.html.twig
{% extends 'LaboAdminBundle::page_admin_generic.html.twig' %}
{% set cssjsloads = 'simple' %}
{% set DEVMODE = (app.environment in ['DEV', 'TEST']) or (is_granted('ROLE_SUPER_ADMIN')) %}
{% import 'LaboAdminBundle:blocks:actions.html.twig' as actions %}

{% block page_heading %}
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-12 m-t-xs">
		<div class="row">
			<div class="col-md-9">
				<h2>{{ actions.htmlicon('calendar', 1, ['m-r-xs']) }}Agenda</h2>
				<ol class="breadcrumb ellipsis">
					<li><a href="{{ path('siteadmin_homepage') }}"><strong>{{ UCfirst('administration'|trans) }}</strong></a></li>
					<li><a href="{{ path('siteadmin_calendar_viewer', {itemSlug: event.ownerObject.slug, class: event.ownerObject.shortname}) }}"><strong>Agenda {{ event.ownerObject.nom }}</strong></a></li>
					<li>Modification {{ event.nom|default('') }}</li>
				</ol>
			</div>
			{% block buttons %}
			{% endblock buttons %}
		</div>
	</div>
</div>
{% endblock page_heading %}

{% block content %}
	{% if event != null %}
	<div class="row animated fadeInDown">
		<div class="col-sm-12">
			{% block ibox %}
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Calendar {{ event.ownerObject.nom }} : {{ event.nom }}</h5>
				</div>
				<div class="ibox-content">
					{# {{ dump(event) }} #}
				</div>
			</div>
			{% endblock ibox %}
		</div>
	</div>
	{% else %}
	<h2>Cet élément <strong>{{ eventSlug|json_encode }}</strong> est introuvable.</h2>
	{% endif %}
	{# {{ dump(test) }} #}
{% endblock content %}

Resources/views/calendar/calendar_tier_viewer.html.twig
{% extends 'LaboAdminBundle::page_admin_generic.html.twig' %}
{% set cssjsloads = 'simple' %}
{% set DEVMODE = (app.environment in ['DEV', 'TEST']) or (is_granted('ROLE_SUPER_ADMIN')) %}
{% import 'LaboAdminBundle:blocks:actions.html.twig' as actions %}

{% block page_heading %}
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-12 m-t-xs">
		<div class="row">
			<div class="col-md-9">
				<h2>{{ actions.htmlicon('calendar', 1, ['m-r-xs']) }}Agenda</h2>
				<ol class="breadcrumb ellipsis">
					<li><a href="{{ path('siteadmin_homepage') }}"><strong>{{ UCfirst('administration'|trans) }}</strong></a></li>
					<li><a href="{{ actions.entiteLink(entity, 'show', type|default(null), type_value_joiner|default(null)) }}"><strong>{{ entity.nom }}</strong></a></li>
					<li>Agenda</li>
				</ol>
			</div>
			{% block buttons %}
			{% endblock buttons %}
		</div>
	</div>
</div>
{% endblock page_heading %}

{% block content %}
	{% if entity != null %}
	<div class="row animated fadeInDown">
		<div class="col-lg-2">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5 class="hidden-lg">Outils <small class="inline"> - Disposez dans l'agenda&nbsp;:</small></h5>
					<h5 class="visible-lg">Outils</h5>
				</div>
				<div class="ibox-content">
					<div class="row">
						<div class="col-xs-12 visible-lg">
							<p>Disposez dans l'agenda&nbsp;:</p>
						</div>
						<div class="col-lg-12 col-xs-6" id='external-events'>
							{% block externals %}
							<div class='external-event text-white' style="background-color:#2572a9;">OUVERT</div>
							<div class='external-event text-white' style="background-color:rgb(95, 181, 30);">LIVRAISONS</div>
							<div class='external-event text-white' style="background-color:#c16625;">Atelier</div>
							{% endblock externals %}
						</div>
						<div class="col-lg-12 col-xs-6">
							{% block calendar_options %}
							<a id="editevent" class="btn btn-white btn-block btn-xs" cal-href="{{ url('siteadmin_calendar_edit', {eventSlug: '__slug__'}) }}"><i class="fa fa-pencil fa-1x"></i> Modifier</a>
							<button id="trash" type="button" class="btn btn-default btn-block btn-xs"><i class="fa fa-trash fa-2x"></i></button>
							{% endblock calendar_options %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-10">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Agenda <strong>{{ entity.nom }}</strong><button id="refresh_calendar" class="btn btn-xs btn-white m-l-sm" style="margin-bottom:0px;"> <i class="fa fa-refresh"></i> </button><span class="m-l-sm" id="calview"></span></h5>
				</div>
				<div class="ibox-content">
					<div id="calendar" cal-url="{{ url('siteadmin_calendar_ajax', {itemSlug: entity.slug, class: entity.shortName}) }}" cal-feed="{{ url('siteadmin_calendar_feed', {itemSlug: entity.slug, class: entity.shortName}) }}" cal-owner="{{ {slug: entity.slug, class: entity.shortName}|json_encode() }}" cal-locale="{{ app.request.locale|default(app.request.defaultLocale) }}"></div>
				</div>
			</div>
		</div>
	</div>
	{% else %}
	<h2>Cet élément <strong>{{ itemSlug|json_encode }}</strong> est introuvable.</h2>
	{% endif %}
	{% if DEVMODE %}
	<div class="row">
		<div class="col-lg-12" id="devwin">
		</div>
	</div>
	{% endif %}
{% endblock content %}